### ISSUE TITLE
Question about Modal Embedding Calculation in "mgcn.py" line 200

### ISSUE THREAD

**Issue by xiao-dun-shou** [demonph10/MGCN#1]
Hello researchers of MGCN,
I am deeply impressed by the excellent performance of your work and am currently studying your MGCN project. I find it very insightful. However, I have a question regarding the Behavior-Aware Fuser implementation in the file `mgcn.py`.
In line 200, the modal embedding is calculated as follows:
**side_embeds = (sep_image_embeds + sep_text_embeds + common_embeds) / 3**
From my understanding, based on the original formula 15 in the paper, the modal embedding should be the sum of the shared embedding and the specific modal embeddings, without dividing by 3. Maybe like this:
**side_embeds = common_embeds + (sep_image_embeds + sep_text_embeds) / 2**

Could you please clarify the reasoning behind this implementation? Is this an experimental adjustment, or is there another rationale behind averaging these embeddings?
I am trying to understand the impact of this specific implementation choice on the model's performance and would greatly appreciate your insight on this matter. Thank you for your time and for sharing such an interesting project with the community. :))))))))

Best regards,
xiaodunshou

**Comment by demonph10** [comment]
Hi, @xiao-dun-shou 
Thank you for your interest in our work. 

The purpose of Equation 15 is to combine modality-specific features and modality-shared features. The equation in the original paper differs slightly from the version we have currently released. After the paper is accepted, we discover that treating modality-shared features and modality-specific features equally could slightly enhance recommendation performance. As a result, we release this improved version with better performance. The underlying principle remains the same, and you have the flexibility to adjust the emphasis on different features to achieve optimal results.

**It is important to note that we have chosen the average pooling method to aggregate modality-specific features and modality-shared features primarily for the sake of simplicity.** We leave the exploration of alternative implementation methods for future work. Looking forward to your further contributions in improving multimodal recommendation performance!

**Comment by xiao-dun-shou** [comment]
Hi, @demonph10 
Thank you for the clarification! It's helpful to understand the reasoning behind the current implementation. Looking forward to seeing more developments in this project.
