### ISSUE TITLE
如何使用KDE绘制二维特征分布

### ISSUE THREAD

**Issue by NanGongNingYi** [demonph10/MGCN#2]
尊敬的作者，您好：

我对您的工作中，使用KDE绘制二维特征分布这部分很感兴趣，想问一下，可否寻求一份代码？
我的邮箱是: gjlin@cnic.cn

感谢，祝您一切顺利！

![image](https://github.com/demonph10/MGCN/assets/61775768/e242f24c-89e9-4aa8-8cc7-fb5dd77a4c17)

**Comment by demonph10** [comment]
非常感谢您对我们工作的关注！

可视化代码实现部分，我们参考了https://github.com/Coder-Yu/SELFRec/issues/14
很感谢[Coder-Yu](https://github.com/Coder-Yu)对我们的帮助！
