### ISSUE TITLE
原始数据获取

### ISSUE THREAD

**Issue by sana-mine** [demonph10/MGCN#3]
作者您好，您的工作做的十分出色，我想请问一下这三个原始数据集的图片和文字应该如何获取呢？能否提供一下处理的代码呢？

**Comment by demonph10** [comment]
您好！

我们直接使用了MMRec所提供的数据集，如果您想获得原始数据，可以从[Amazon](https://jmcauley.ucsd.edu/data/amazon/links.html)下载。

可以参考如下链接：
https://github.com/enoche/MMRec/tree/master/preprocessing

**Comment by sana-mine** [comment]
十分感谢您的回答，也就是说这三个数据集其实是对应amazon这个大数据集中的三个类别是吧？

**Comment by demonph10** [comment]
是的
