### ISSUE TITLE
ask about the parameters

### ISSUE THREAD

**Issue by Dylanqxh** [demonph10/MGCN#4]
Hello author, your work is excellent. I would like to ask about the parameters for each data set to achieve the best experimental results. Can you provide them?

**Comment by demonph10** [comment]
Thank you for your attention to our work.
We found that in most cases, cl-loss has the best performance at 0.01, while others can refer to our default settings.

**Comment by Dylanqxh** [comment]
Thank you for your thoughtful response, I truly appreciate your help!

**Comment by Gs0098** [comment]
> Thank you for your thoughtful response, I truly appreciate your help!感谢您的深思熟虑的回答，我真的很感激您的帮助！
请问你复现的如何

**Comment by demonph10** [comment]
@sjc-dd 如果在复现中遇到什么问题，欢迎提出，我们会尽力解答。同时也期待关注我们新发表在AAAI'25上的工作[Mind Individual Information! Principal Graph Learning for Multimedia Recommendation](https://ojs.aaai.org/index.php/AAAI/article/view/33429)，我们也提供了开源代码https://github.com/demonph10/PGL

**Comment by Gs0098** [comment]
@demonph10 感谢作者！ 我复现了你们的代码  请问我们在训练时最后的█████████████ BEST ████████████████   就是测试集的平均结果吧（我看了相应代码 感觉是 但不是很确定）我会持续关注你们的最新工作的！已经star 感谢开源和回复！

**Comment by demonph10** [comment]
> [@demonph10](https://github.com/demonph10) 感谢作者！ 我复现了你们的代码 请问我们在训练时最后的█████████████ BEST ████████████████ 就是测试集的平均结果吧（我看了相应代码 感觉是 但不是很确定）我会持续关注你们的最新工作的！已经star 感谢开源和回复！

@sjc-dd 训练最后显示的是在固定随机数种下进行单次实验后，测试集上进行测试的结果。
如果需要多次实验的平均结果，可以尝试更换不同的随机数种，重复10次实验，计算测试集结果的平均值。
感谢对我们工作的关注！

**Comment by demonph10** [comment]
> 请问您们论文中的结果就是按照你说的取10次实验得到的平均结果吗？
> 
> 
> 
> 
> 孙继承
> ***@***.***

是的

**Comment by Gs0098** [comment]
> > 请问您们论文中的结果就是按照你说的取10次实验得到的平均结果吗？
> > 孙继承
> > _**@**_.***
> 
> 是的

大佬你好 我有一个问题，在进行实验时 我们的embding_size 和batch_size 应该和对比模型保持一致吧 就都是64 和2048 不能调（调了会带来性能上的提升 是这样嘛？ 不公平对比实验）

**Comment by demonph10** [comment]
> > > 请问您们论文中的结果就是按照你说的取10次实验得到的平均结果吗？
> > > 孙继承
> > > _**@**_.***
> > 
> > 
> > 是的
> 
> 大佬你好 我有一个问题，在进行实验时 我们的embding_size 和batch_size 应该和对比模型保持一致吧 就都是64 和2048 不能调（调了会带来性能上的提升 是这样嘛？ 不公平对比实验）

一般来说，大家都是这么设置的，这样比较比较公平，因为embding_size越大效果通常会越好。如果您修改了这个参数，最好在实现部分说清楚，并在超参数分析里进行论证。
